# BaseLine Phase 4

In [5]:
import pandas as pd

In [6]:
baseline_phase4 = pd.DataFrame({
    "Model": [
        "Naive (Lag 1)",
        "Previous-Day (Lag 24)",
        "Previous-Week (Lag 168)",
        "24-Hour Moving Average"
    ],
    "MAE (MW)": [
        1207.86,
        2267.30,
        3542.48,
        3501.35
    ],
    "RMSE (MW)": [
        1808.41,
        3120.65,
        4893.50,
        4456.37
    ],
    "MAPE (%)": [
        3.86,
        7.12,
        10.96,
        11.44
    ],
    "R²": [
        0.92,
        0.75,
        0.39,
        0.49
    ]
})

baseline_phase4

                     Model  MAE (MW)  RMSE (MW)  MAPE (%)    R²
0            Naive (Lag 1)   1207.86    1808.41      3.86  0.92
1    Previous-Day (Lag 24)   2267.30    3120.65      7.12  0.75
2  Previous-Week (Lag 168)   3542.48    4893.50     10.96  0.39
3   24-Hour Moving Average   3501.35    4456.37     11.44  0.49

# Phase 5 all sequence comparision

In [7]:

results = [
    # Sequence 24
    [24, "RNN",     2846.4260, 14315979.70, 3783.6464,  9.4754, 0.6564,  947.4050],
    [24, "LSTM",    3283.3430, 18761523.22, 4331.4574, 11.1425, 0.5498, 2062.5279],
    [24, "GRU",     4117.8057, 26966376.54, 5192.9160, 14.1280, 0.3528, 2411.6062],
    [24, "Bi-LSTM", 2695.5889, 13269242.90, 3642.6972,  8.9727, 0.6816, 1326.5356],

    # Sequence 48
    [48, "RNN",     3113.5025, 17937065.53, 4235.2173, 10.3899, 0.5699,  951.4076],
    [48, "LSTM",    3116.8660, 17748782.63, 4212.9304, 10.4615, 0.5744, 1788.9554],
    [48, "GRU",     3431.3661, 20900880.73, 4571.7481, 11.5989, 0.4989, 1739.2754],
    [48, "Bi-LSTM", 2483.9147, 11166770.97, 3341.6719,  8.3482, 0.7323, 1040.4537],

    # Sequence 168
    [168, "RNN",     2505.4730, 11760047.90, 3429.2926,  8.3724, 0.7188, 1325.3893],
    [168, "LSTM",    3084.0395, 16838518.86, 4103.4764, 10.4509, 0.5973, 1673.6073],
    [168, "GRU",     3645.5561, 23684668.02, 4866.6896, 12.3473, 0.4336, 2286.3822],
    [168, "Bi-LSTM", 2600.2790, 12048502.91, 3471.0953,  8.8179, 0.7119, 1223.3555],
]

results_df = pd.DataFrame(
    results,
    columns=[
        "Sequence_Length",
        "Model",
        "MAE",
        "MSE",
        "RMSE",
        "MAPE",
        "R2",
        "Bias"
    ]
)

results_df

,Sequence_Length,Model,MAE,MSE,RMSE,MAPE,R2,Bias
0,24,RNN,2846.4260,14315979.70,3783.6464,9.4754,0.6564,947.4050
1,24,LSTM,3283.3430,18761523.22,4331.4574,11.1425,0.5498,2062.5279
2,24,GRU,4117.8057,26966376.54,5192.9160,14.1280,0.3528,2411.6062
3,24,Bi-LSTM,2695.5889,13269242.90,3642.6972,8.9727,0.6816,1326.5356
4,48,RNN,3113.5025,17937065.53,4235.2173,10.3899,0.5699,951.4076
5,48,LSTM,3116.8660,17748782.63,4212.9304,10.4615,0.5744,1788.9554
6,48,GRU,3431.3661,20900880.73,4571.7481,11.5989,0.4989,1739.2754
7,48,Bi-LSTM,2483.9147,11166770.97,3341.6719,8.3482,0.7323,1040.4537
8,168,RNN,2505.4730,11760047.90,3429.2926,8.3724,0.7188,1325.3893
9,168,LSTM,3084.0395,16838518.86,4103.4764,10.4509,0.5973,1673.6073
10,168,GRU,3645.5561,23684668.02,4866.6896,12.3473,0.4336,2286.3822
11,168,Bi-LSTM,2600.2790,12048502.91,3471.0953,8.8179,0.7119,1223.3555

In [8]:
results_df.sort_values(by="R2", ascending=False)

,Sequence_Length,Model,MAE,MSE,RMSE,MAPE,R2,Bias
7,48,Bi-LSTM,2483.9147,11166770.97,3341.6719,8.3482,0.7323,1040.4537
8,168,RNN,2505.4730,11760047.90,3429.2926,8.3724,0.7188,1325.3893
11,168,Bi-LSTM,2600.2790,12048502.91,3471.0953,8.8179,0.7119,1223.3555
3,24,Bi-LSTM,2695.5889,13269242.90,3642.6972,8.9727,0.6816,1326.5356
0,24,RNN,2846.4260,14315979.70,3783.6464,9.4754,0.6564,947.4050
9,168,LSTM,3084.0395,16838518.86,4103.4764,10.4509,0.5973,1673.6073
5,48,LSTM,3116.8660,17748782.63,4212.9304,10.4615,0.5744,1788.9554
4,48,RNN,3113.5025,17937065.53,4235.2173,10.3899,0.5699,951.4076
1,24,LSTM,3283.3430,18761523.22,4331.4574,11.1425,0.5498,2062.5279
6,48,GRU,3431.3661,20900880.73,4571.7481,11.5989,0.4989,1739.2754
10,168,GRU,3645.5561,23684668.02,4866.6896,12.3473,0.4336,2286.3822
2,24,GRU,4117.8057,26966376.54,5192.9160,14.1280,0.3528,2411.6062

# After Enhancement in Phase 6 the best model in each

In [1]:
import pandas as pd

data = [
    [
        "Bi-LSTM 48",
        "Optimizer",
        "RMSprop",
        1771.425878130128,
        5619109.234146657,
        2370.4660373324605,
        5.793036501472333,
        0.8653722535707811,
        72.40864041789405
    ],
    
    [
        "LSTM 168",
        "Hyperparameter Tuning",
        "Tuned",
        1947.5263563790731,
        6851497.791196226,
        2617.5365883204436,
        6.4726604688660565,
        0.8362789750607131,
        696.291991417626
    ],
    
    [
        "SimpleRNN 168",
        "Additional Layers",
        "128, 64",
        1785.3066056561163,
        5417045.163471879,
        2327.4546533653197,
        6.006679776783465,
        0.870556159640653,
        843.6400840578602
    ],
    
    [
        "Bi-LSTM 168",
        "Early Stopping",
        "Enabled",
        1716.292653290363,
        5244531.318543965,
        2290.0941724182358,
        5.66646222721273,
        0.8746784908985142,
        216.42199049619254
    ]
]

df_top_models = pd.DataFrame(
    data,
    columns=[
        "Model",
        "Experiment",
        "Configuration",
        "MAE",
        "MSE",
        "RMSE",
        "MAPE",
        "R2",
        "Bias"
    ]
)

df_top_models

,Model,Experiment,Configuration,MAE,MSE,RMSE,MAPE,R2,Bias
0,Bi-LSTM 48,Optimizer,RMSprop,1771.425878,5.619109e+06,2370.466037,5.793037,0.865372,72.408640
1,LSTM 168,Hyperparameter Tuning,Tuned,1947.526356,6.851498e+06,2617.536588,6.472660,0.836279,696.291991
2,SimpleRNN 168,Additional Layers,"128, 64",1785.306606,5.417045e+06,2327.454653,6.006680,0.870556,843.640084
3,Bi-LSTM 168,Early Stopping,Enabled,1716.292653,5.244531e+06,2290.094172,5.666462,0.874678,216.421990

In [2]:
df_top_models.sort_values(by="R2", ascending=False)

,Model,Experiment,Configuration,MAE,MSE,RMSE,MAPE,R2,Bias
3,Bi-LSTM 168,Early Stopping,Enabled,1716.292653,5.244531e+06,2290.094172,5.666462,0.874678,216.421990
2,SimpleRNN 168,Additional Layers,"128, 64",1785.306606,5.417045e+06,2327.454653,6.006680,0.870556,843.640084
0,Bi-LSTM 48,Optimizer,RMSprop,1771.425878,5.619109e+06,2370.466037,5.793037,0.865372,72.408640
1,LSTM 168,Hyperparameter Tuning,Tuned,1947.526356,6.851498e+06,2617.536588,6.472660,0.836279,696.291991